name: Hello Actions

on: [push]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 打印 Hello, GitHub Actions!
        run: echo "Hello, GitHub Actions!"
